/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.pou.presentacion;
import java.util.ArrayList;
import java.util.List;
import mx.itson.pou.entidades.Pou;
import mx.itson.pou.entidades.Producto;
import mx.itson.pou.negocio.Negocio;
/**
 *
 * @author SaulUrias
 */
public class Cocina extends javax.swing.JFrame {
    
    
    Pou pou = new Pou(5000,25,100,100,100);
    
    Producto carne = new Producto(1,"carne",150,25,0,-10,0,6);
    Producto hamburguesa = new Producto(2,"Hamburguesa", 100, 20, 0, -10, 0, 5);
    Producto platano = new Producto(3,"platano",50,15,0,-5,0,10);
    
    List<Producto> productos = new ArrayList();
    int posicionProducto = 0;
    
    
    
    
    /**
     * Creates new form kitchen
     */
    public Cocina() {
        initComponents();

        productos.add(hamburguesa);
        productos.add(carne);
        productos.add(platano);
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCocina = new javax.swing.JPanel();
        lblImagenMoneda = new javax.swing.JLabel();
        lblImagePou = new javax.swing.JLabel();
        btn_Refrigerador = new javax.swing.JButton();
        btn_Comida = new javax.swing.JButton();
        lblRefrigerador = new javax.swing.JLabel();
        btn_Tienda = new javax.swing.JButton();
        progressHambre = new javax.swing.JProgressBar();
        progressSalud = new javax.swing.JProgressBar();
        progressEnergia = new javax.swing.JProgressBar();
        progressFelicidad = new javax.swing.JProgressBar();
        lblImagenHambrePou = new javax.swing.JLabel();
        lblImagenSalud = new javax.swing.JLabel();
        lblImagenEnergia = new javax.swing.JLabel();
        lblImagenFelicidad = new javax.swing.JLabel();
        lblCantidadComida = new javax.swing.JLabel();
        lblTienda = new javax.swing.JLabel();
        btn_Siguiente = new javax.swing.JButton();
        btn_Anterior = new javax.swing.JButton();
        btn_Comer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cocina");
        setBackground(new java.awt.Color(255, 153, 153));
        setMinimumSize(new java.awt.Dimension(350, 500));

        panelCocina.setBackground(new java.awt.Color(255, 153, 153));
        panelCocina.setLayout(null);

        lblImagenMoneda.setFont(new java.awt.Font("Seravek", 1, 14)); // NOI18N
        lblImagenMoneda.setForeground(new java.awt.Color(255, 255, 0));
        lblImagenMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coin.png"))); // NOI18N
        lblImagenMoneda.setText("x 5000");
        panelCocina.add(lblImagenMoneda);
        lblImagenMoneda.setBounds(6, 14, 86, 34);

        lblImagePou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pou_estudiante.png"))); // NOI18N
        panelCocina.add(lblImagePou);
        lblImagePou.setBounds(100, 140, 155, 174);

        btn_Refrigerador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refri.png"))); // NOI18N
        btn_Refrigerador.setBorderPainted(false);
        btn_Refrigerador.setContentAreaFilled(false);
        btn_Refrigerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefrigeradorActionPerformed(evt);
            }
        });
        panelCocina.add(btn_Refrigerador);
        btn_Refrigerador.setBounds(10, 390, 82, 91);

        btn_Comida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hamburguesa.png"))); // NOI18N
        btn_Comida.setBorderPainted(false);
        btn_Comida.setContentAreaFilled(false);
        btn_Comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComidaActionPerformed(evt);
            }
        });
        panelCocina.add(btn_Comida);
        btn_Comida.setBounds(130, 380, 74, 68);

        lblRefrigerador.setFont(new java.awt.Font("Seravek", 1, 14)); // NOI18N
        lblRefrigerador.setText("Refrigerador");
        panelCocina.add(lblRefrigerador);
        lblRefrigerador.setBounds(10, 480, 90, 18);

        btn_Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shop.png"))); // NOI18N
        btn_Tienda.setBorderPainted(false);
        btn_Tienda.setContentAreaFilled(false);
        btn_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TiendaActionPerformed(evt);
            }
        });
        panelCocina.add(btn_Tienda);
        btn_Tienda.setBounds(250, 390, 93, 86);

        progressHambre.setToolTipText("");
        progressHambre.setValue(20);
        panelCocina.add(progressHambre);
        progressHambre.setBounds(100, 50, 40, 20);

        progressSalud.setValue(100);
        panelCocina.add(progressSalud);
        progressSalud.setBounds(160, 50, 40, 20);

        progressEnergia.setValue(100);
        panelCocina.add(progressEnergia);
        progressEnergia.setBounds(220, 50, 40, 20);

        progressFelicidad.setValue(100);
        panelCocina.add(progressFelicidad);
        progressFelicidad.setBounds(280, 50, 40, 20);

        lblImagenHambrePou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hambre.png"))); // NOI18N
        panelCocina.add(lblImagenHambrePou);
        lblImagenHambrePou.setBounds(110, 10, 30, 33);

        lblImagenSalud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart.png"))); // NOI18N
        panelCocina.add(lblImagenSalud);
        lblImagenSalud.setBounds(160, 10, 35, 30);

        lblImagenEnergia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/energy.png"))); // NOI18N
        panelCocina.add(lblImagenEnergia);
        lblImagenEnergia.setBounds(210, 0, 49, 50);

        lblImagenFelicidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/felicidad.png"))); // NOI18N
        panelCocina.add(lblImagenFelicidad);
        lblImagenFelicidad.setBounds(280, 10, 40, 40);

        lblCantidadComida.setFont(new java.awt.Font("Seravek", 1, 14)); // NOI18N
        lblCantidadComida.setText("Hamburguesa X 5");
        panelCocina.add(lblCantidadComida);
        lblCantidadComida.setBounds(120, 450, 110, 18);

        lblTienda.setFont(new java.awt.Font("Seravek", 1, 14)); // NOI18N
        lblTienda.setText("Tienda");
        panelCocina.add(lblTienda);
        lblTienda.setBounds(280, 480, 50, 18);

        btn_Siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right_arrow.png"))); // NOI18N
        btn_Siguiente.setBorderPainted(false);
        btn_Siguiente.setContentAreaFilled(false);
        btn_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SiguienteActionPerformed(evt);
            }
        });
        panelCocina.add(btn_Siguiente);
        btn_Siguiente.setBounds(280, 230, 80, 40);

        btn_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left_arrow.png"))); // NOI18N
        btn_Anterior.setBorderPainted(false);
        btn_Anterior.setContentAreaFilled(false);
        panelCocina.add(btn_Anterior);
        btn_Anterior.setBounds(0, 229, 80, 40);

        btn_Comer.setBackground(new java.awt.Color(255, 153, 153));
        btn_Comer.setFont(new java.awt.Font("Seravek", 1, 14)); // NOI18N
        btn_Comer.setText("Comer");
        btn_Comer.setOpaque(true);
        btn_Comer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComerActionPerformed(evt);
            }
        });
        panelCocina.add(btn_Comer);
        btn_Comer.setBounds(120, 470, 97, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCocina, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCocina, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RefrigeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefrigeradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RefrigeradorActionPerformed

    private void btn_ComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComidaActionPerformed
        //AlimentarPou();
        obtenerProductos();
    }//GEN-LAST:event_btn_ComidaActionPerformed

    private void btn_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TiendaActionPerformed
        EstanteRefrigerador er = new EstanteRefrigerador();
        er.setSize(369, 297);
        er.setVisible(true);
    }//GEN-LAST:event_btn_TiendaActionPerformed

    private void btn_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SiguienteActionPerformed
       // Laboratorio laboratorio = new Laboratorio();
       // laboratorio.setVisible(true);
        
        //this.setVisible(false);
    }//GEN-LAST:event_btn_SiguienteActionPerformed

    private void btn_ComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComerActionPerformed
        
        if (posicionProducto > 3 || posicionProducto == 0) {
            AlimentarPou(productos.get(0));
        }else {
            AlimentarPou(productos.get(posicionProducto-1));
        }  
    }//GEN-LAST:event_btn_ComerActionPerformed

    
    public void AlimentarPou(Producto producto){
   
     Negocio comida = new Negocio();
     
     comida.Comer(producto, pou);
     progressHambre.setValue(pou.getValorHambre());
     progressSalud.setValue(pou.getValorSalud());
     progressEnergia.setValue(pou.getValorEnergia());
     progressFelicidad.setValue(pou.getValorFelicidad());
     lblCantidadComida.setText(producto.getNombre() + " X " + producto.getCantidad());
    }
    
    public void obtenerProductos(){
        
        if (posicionProducto > 2) {
            lblCantidadComida.setText(productos.get(0).getNombre() + " X " + productos.get(0).getCantidad());
        
            btn_Comida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+productos.get(0).getNombre()+".png")));
            posicionProducto = 0;
        }else{
            lblCantidadComida.setText(productos.get(posicionProducto).getNombre() + " X " + productos.get(posicionProducto).getCantidad());
        
            btn_Comida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+productos.get(posicionProducto).getNombre()+".png")));
            
            posicionProducto++;
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anterior;
    private javax.swing.JButton btn_Comer;
    private javax.swing.JButton btn_Comida;
    private javax.swing.JButton btn_Refrigerador;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.JButton btn_Tienda;
    private javax.swing.JLabel lblCantidadComida;
    private javax.swing.JLabel lblImagePou;
    private javax.swing.JLabel lblImagenEnergia;
    private javax.swing.JLabel lblImagenFelicidad;
    private javax.swing.JLabel lblImagenHambrePou;
    private javax.swing.JLabel lblImagenMoneda;
    private javax.swing.JLabel lblImagenSalud;
    private javax.swing.JLabel lblRefrigerador;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JPanel panelCocina;
    private javax.swing.JProgressBar progressEnergia;
    private javax.swing.JProgressBar progressFelicidad;
    private javax.swing.JProgressBar progressHambre;
    private javax.swing.JProgressBar progressSalud;
    // End of variables declaration//GEN-END:variables
}
